### ISSUE TITLE
Ogg #4 --> Tier 1 creation of laser has no place for wavelength

### ISSUE THREAD

**Issue by stephenogg** [WU-BIMAC/MicroMetaApp-React#365]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to add a fluorescence light source, I can't add the wavelength, but I have to add the power? I know this changes depending on the tier level, but if I'm adding a fluorescence light source laser or led, I'm more likely to know the wavelength than the power. My opinion is that the wavelength is more fundamental than power when thinking about the excitation of fluorescence.

**Describe the solution you'd like**
I guess I'm questioning two things:
Why require power at tier 1?
Why not require wavelength at tier 1?

**Comment by strambc** [comment]
Hi thank you for your comment.
I have entered a proposed MODEL CHANGE to describe this issue here:
https://github.com/WU-BIMAC/MicroscopyMetadata4DNGuidelines/issues/41

Also keep in mind that it is always possible to open an Instrument at at higher Tier level and then validate at a lower level.

Example: Open an instrument at Tie3
Choose Tier 1 using the "Validate @Tier1" selector at the bottom


https://user-images.githubusercontent.com/4050585/113613439-3c9ce580-961f-11eb-9927-a12efbf96c2f.mov
