### ISSUE TITLE
Removing Dichroic does not invalidate FilterSet

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#47]
When removed Dichroic 1 the Filteset that referred to Dichroic 1 did not get invalidated (the red box did not appear).
When editing the component, now it does not allow to Confirm.

SHOULD GIVE WARNING THAT CORRESPONDING ELEMENT HAS BEEN REMOVED

**Comment by strambc** [comment]
I do not think this is a bug.
However the feature should be added.

**Comment by Akramhar** [comment]
the microscope now should get updated correctly when a link is broken.
there is no warning on window if the field was not required to begin with.
if the field was require it should fail to validate and consequently the red border should appear.
i'm not totally sure about this part due to the fact we don't have required link on the model atm.

**Comment by strambc** [comment]
![image](https://user-images.githubusercontent.com/4050585/69766685-1e7bc700-1147-11ea-8b99-82dc325cdb54.png)

**Comment by strambc** [comment]
Let's discuss after next week
